version: "3"

networks:
  admin:

volumes:
  certificates:

services:
  nginx:
    container_name: nginx
    build:
      context: https://github.com/FunkySheepStudio/Infra.git#:nginx
      dockerfile: DockerFile
    volumes:
      - certificates:/etc/letsencrypt/live/:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - admin
  admin-server:
    depends_on:
      - nginx
    container_name: funkysheep-admin
    build:
      context: https://github.com/FunkySheepStudio/Infra.git#:admin.funkysheep.net
      dockerfile: DockerFile
    ports:
      - "80"
      - "443"
    networks:
      - admin