
version: "3"

networks:
  everse:

services:
  nginx:
    container_name: nginx
    build:
      context: https://github.com/FunkySheepStudio/Infra.git#:nginx
      dockerfile: DockerFile
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - everse
    restart: always
  everse-server:
    depends_on:
      - nginx
    container_name: funkysheep-everse
    build:
      context: /var/www/everse.funkysheep.net/
      dockerfile: DockerFile
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    ports:
      - "8080"
      - "443"
      - "7777:7777"
    networks:
      - everse
    restart: always