
version: "3"

networks:
  admin:

services:
  nginx:
    container_name: nginx
    build:
      context: https://github.com/FunkySheepStudio/Infra.git#:nginx
      dockerfile: DockerFile
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - admin
  admin-server:
    depends_on:
      - nginx
    container_name: funkysheep-admin
    build:
      context: /var/www/admin.funkysheep.net/
      dockerfile: DockerFile
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    ports:
      - "8080"
      - "443"
    networks:
      - admin