FROM ubuntu
RUN \
    apt-get install software-properties-common
    add-apt-repository ppa:bitcoin/bitcoin && \
    apt-get update && \
    apt-get install -y bitcoind
CMD ["/usr/bin/bitcoind", "-datadir=/var/bitcoin/data/", "--printtoconsole"]
