FROM dockerfile/ubuntu
RUN \
    add-apt-repository ppa:bitcoin/bitcoin && \
    apt-get update && \
    apt-get install -y bitcoind
CMD ["/usr/bin/bitcoind", "-datadir=/var/bitcoin/data/", "--printtoconsole"]