name: install-certbot
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          echo ---- Update the server ---
          sudo apt-get update
          sudo apt-get -y upgrade
          echo ---- Install certbot ---
          sudo apt-get -y install certbot